"""RunSpec → harness patch 翻译器。

把 control-plane 编译出的 RunSpec（model/system_prompt/tools/skills）
转换为 harness headless 可用的 cordis patch YAML 片段。
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

import json
import tempfile

# 内置工具的插件路径映射：工具 ID → harness 插件 .ts 文件路径。
# 若某个工具没有映射，则该工具不注入（headless 仍可自主规划）。
TOOL_PLUGIN_PATHS: Dict[str, str] = {
    "tool_calculator": "D:/projects/react_demo/auto_react_aigc/harness-plugins/calculator.ts",
    "query_records": "D:/projects/deepseek_harness学习/deepseek-harness/scratch-plugin/src/business-data-plugin.ts",
    "aggregate_records": "D:/projects/deepseek_harness学习/deepseek-harness/scratch-plugin/src/business-data-plugin.ts",
}


class PatchGenerator:
    """根据 RunSpec 生成 harness headless 的 --patch 配置。"""

    def __init__(
        self,
        aimp_api_base: str,
        model: str,
        tool_plugin_paths: Optional[Dict[str, str]] = None,
    ):
        self.aimp_api_base = aimp_api_base
        self.model = model
        self.tool_plugin_paths = tool_plugin_paths or TOOL_PLUGIN_PATHS

    def build_patch_yaml(self, runspec: Dict[str, Any]) -> str:
        """生成 patch YAML 文本。

        - 默认模型路由指向 AIMP Qwen。
        - 注入 runspec.tools 中命中的业务工具插件。
        - system_prompt 通过 dsh 的 system-prompt 插件注入。
        """
        tools = runspec.get("tools", []) or []
        # 去重且匹配到映射的工具
        plugin_paths = self._resolve_tool_plugins(tools)
        system_prompt = (runspec.get("system_prompt") or "").strip()

        lines = ["# auto-generated by harness-bridge", "- insert:"]
        right = 0

        if system_prompt:
            # 通过 dsh-system-prompt 插件注入自定义系统提示词
            lines.append(f"    - id: system-prompt")
            lines.append(f"      name: '@deepseek-ai/dsh-system-prompt'")
            lines.append(f"      config:")
            lines.append(f"        text: {json.dumps(system_prompt, ensure_ascii=False)}")

        for i, path in enumerate(plugin_paths):
            lines.append(f"    - id: biz-tool-{i}")
            lines.append(f"      name: {json.dumps(path)}")

        lines.append(f"    - id: llm-pi-ai")
        lines.append(f"      name: '@deepseek-ai/dsh-llm-pi-ai'")
        lines.append(f"      config:")
        lines.append(f"        providers:")
        lines.append(f"          aimp-qwen:")
        lines.append(f"            apiKeyEnv: AIMP_OPENAI_API_KEY")
        lines.append(f"            api: openai-completions")
        lines.append(f"            baseURL: {json.dumps(self.aimp_api_base)}")
        lines.append(f"            models:")
        lines.append(f"              - id: {json.dumps(self.model)}")
        lines.append(f"            compat:")
        lines.append(f"              supportsDeveloperRole: false")
        lines.append(f"              maxTokensField: max_tokens")

        lines.append(f"    - id: agent-default-model")
        lines.append(f"      name: '@deepseek-ai/dsh-agent-default-model'")
        lines.append(f"      config:")
        lines.append(f"        provider: aimp-qwen")
        lines.append(f"        model: {json.dumps(self.model)}")

        return "\n".join(lines)

    def _resolve_tool_plugins(self, tool_ids: List[str]) -> List[str]:
        """把工具 ID 解析为插件路径，去重且保序。"""
        seen: set[str] = set()
        result: List[str] = []
        for tid in tool_ids:
            path = self.tool_plugin_paths.get(tid)
            if path and path not in seen:
                seen.add(path)
                result.append(path)
        return result

    def write_patch(self, runspec: Dict[str, Any]) -> str:
        """生成 patch 并写入临时文件，返回该文件路径。"""
        content = self.build_patch_yaml(runspec)
        fd = tempfile.NamedTemporaryFile(
            mode="w", suffix=".yml", prefix="runspec-", delete=False, encoding="utf-8"
        )
        fd.write(content)
        fd.close()
        return fd.name